name: frontend

ports:
  - port: 5000
    targetPort: 5000
serviceType: NodePort
container:
  command: frontend
  image: hotelreservation
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
